/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Customer {
  'name' : string,
  'address' : string,
  'customerId' : bigint,
  'phone' : string,
}
export interface Invoice {
  'id' : bigint,
  'customerName' : string,
  'total' : bigint,
  'taxPercent' : bigint,
  'date' : Time,
  'createdAt' : Time,
  'customerAddress' : string,
  'notes' : string,
  'phone' : string,
  'items' : Array<InvoiceItem>,
  'taxAmount' : bigint,
  'subtotal' : bigint,
}
export interface InvoiceItem {
  'qty' : bigint,
  'name' : string,
  'unitPrice' : bigint,
}
export interface StoreEntry {
  'principal' : Principal,
  'storeProfile' : StoreProfile,
}
export interface StoreProfile {
  'cin' : string,
  'fssai' : string,
  'storeId' : bigint,
  'isActive' : boolean,
  'gstin' : string,
  'address' : string,
  'storeName' : string,
  'mobile' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  'createInvoice' : ActorMethod<[Invoice], bigint>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllStores' : ActorMethod<[], Array<StoreEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getMyInvoices' : ActorMethod<[], Array<Invoice>>,
  'getMyStoreProfile' : ActorMethod<[], [] | [StoreProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isFirstRunNeeded' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'resetAdminClaim' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveStoreProfile' : ActorMethod<
    [string, string, string, string, string, string],
    StoreProfile
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStoreStatus' : ActorMethod<[Principal, boolean], undefined>,
  'setUserStatus' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];