/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const InvoiceItem = IDL.Record({
  'qty' : IDL.Nat,
  'name' : IDL.Text,
  'unitPrice' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'total' : IDL.Nat,
  'taxPercent' : IDL.Nat,
  'date' : Time,
  'createdAt' : Time,
  'customerAddress' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'taxAmount' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const Customer = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'customerId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const StoreProfile = IDL.Record({
  'cin' : IDL.Text,
  'fssai' : IDL.Text,
  'storeId' : IDL.Nat,
  'isActive' : IDL.Bool,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'storeName' : IDL.Text,
  'mobile' : IDL.Text,
});
export const StoreEntry = IDL.Record({
  'principal' : IDL.Principal,
  'storeProfile' : StoreProfile,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllStores' : IDL.Func([], [IDL.Vec(StoreEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getMyStoreProfile' : IDL.Func([], [IDL.Opt(StoreProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isFirstRunNeeded' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'resetAdminClaim' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveStoreProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [StoreProfile],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStoreStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'setUserStatus' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const InvoiceItem = IDL.Record({
    'qty' : IDL.Nat,
    'name' : IDL.Text,
    'unitPrice' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'total' : IDL.Nat,
    'taxPercent' : IDL.Nat,
    'date' : Time,
    'createdAt' : Time,
    'customerAddress' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'taxAmount' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const Customer = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'customerId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const StoreProfile = IDL.Record({
    'cin' : IDL.Text,
    'fssai' : IDL.Text,
    'storeId' : IDL.Nat,
    'isActive' : IDL.Bool,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'storeName' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const StoreEntry = IDL.Record({
    'principal' : IDL.Principal,
    'storeProfile' : StoreProfile,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllStores' : IDL.Func([], [IDL.Vec(StoreEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getMyStoreProfile' : IDL.Func([], [IDL.Opt(StoreProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isFirstRunNeeded' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'resetAdminClaim' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveStoreProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [StoreProfile],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStoreStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'setUserStatus' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };